spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vueserver-api?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.vueapiserver.shop.entity
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:dao/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
server:
  port: 8082
# 配置分页参数
page:
  pageNum: pageNum
  pageSize: pageSize
  orderByColumn: orderByColumn
  isAsc: isAsc